project_name: inbucket

release:
  github:
    owner: inbucket
    name: inbucket
  name_template: '{{.Tag}}'

before:
  hooks:
    - go mod download

builds:
  - id: inbucket
    binary: inbucket
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    main: ./cmd/inbucket
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  - id: inbucket-client
    binary: inbucket-client
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    main: ./cmd/client
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: tarball
    format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - etc/**
      - ui/dist/**
      - ui/greeting.html

nfpms:
  - formats:
      - deb
      - rpm
    vendor: inbucket.org
    homepage: https://www.inbucket.org/
    maintainer: github@hillyerd.com
    description: All-in-one disposable webmail service.
    license: MIT
    contents:
      - src: "ui/dist/**"
        dst: "/usr/share/inbucket/ui"
      - src: "etc/linux/inbucket.service"
        dst: "/lib/systemd/system/inbucket.service"
        type: config|noreplace
      - src: "ui/greeting.html"
        dst: "/etc/inbucket/greeting.html"
        type: config|noreplace

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

dist: dist
